name: resource_portable
version: 3.1.1
description: Reading resource data from files in a portable way (VM, Web, Flutter and native).
homepage: https://github.com/gmpassos/resource_portable

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.18.0
  path: ^1.9.1
  typed_data: ^1.4.0

dev_dependencies:
  test: ^1.25.15
  lints: ^5.0.0
  dependency_validator: ^3.2.3
