name: resource_portable
version: 3.1.4
description: Reading resource data from files in a portable way (VM, Web, Flutter and native).
homepage: https://github.com/gmpassos/resource_portable

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.19.1
  path: ^1.9.1
  typed_data: ^1.4.0
  http: ^1.6.0

dev_dependencies:
  test: ^1.29.0
  lints: ^5.1.1
  dependency_validator: ^5.0.4
