name: resource_portable
version: 3.0.0
description: Reading resource data from (package and other) files (portable fork for Web).
homepage: https://github.com/gmpassos/resource_portable

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  typed_data: ^1.3.0

dev_dependencies:
  test: ^1.16.5
  pedantic: ^1.11.0
