name: resource_portable
version: 3.0.3
description: Reading resource data from files in a portable way (VM, Web, Flutter and native).
homepage: https://github.com/gmpassos/resource_portable

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  path: ^1.8.3
  typed_data: ^1.3.1

dev_dependencies:
  test: ^1.22.1
  lints: ^2.0.1
  dependency_validator: ^3.2.2
