name: resource_portable
version: 2.1.7
description: Reading resource data from (package and other) files (portable fork for Web).
homepage: https://github.com/gmpassos/resource_portable

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  typed_data: "^1.0.0"
dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.8.0
